Raf
InfraBlockchain/infrablockspace-docs pull request #21
Opened 2023-10-12 08:03 UTC by cocoyoon

## Changes
- [x] 부자연스러운 표현 수정
- [ ] 로컬 이미지 추가

2023-10-13 11:08 UTC, sweatpotato13 requested changes

2023-10-13 11:08 UTC, sweatpotato13 commented on ko/build/build-a-deterministic-runtime.ko.md
> +그러나 컴파일러가 기본적으로 빌드하는 WebAssembly 바이너리는 결정론적(deterministic)하지 않습니다.
`결정론적(deterministic)하지 않습니다.` 는 조금 어색한거 같아서 
`결정론적(deterministic)이지 않습니다.` 가 좋을 것 같습니다.

2023-10-13 11:08 UTC, sweatpotato13 commented on ko/build/tx-weights-fees.ko.md
> +일부 트랜잭션는 다른 전략으로 리소스를 제한할 필요가 있습니다.
트랜잭션는 > 트랜잭션은

2023-10-13 11:08 UTC, sweatpotato13 commented on ko/build/randomness.ko.md
> +## 난수 생성 생성 및 사용
`난수 생성 및 사용` 정도로 하면 어떨까요?

2023-10-17 03:00 UTC, sweatpotato13 commented on ko/build/application-development.ko.md
> +다음 단계로 넘어가기
`## 다음 단계로 넘어가기` 처럼 앞에 ##을 붙여 주는것이 좋을 것 같습니다.

다른 문서에는 붙어있는 것 같은데 안붙어 있는 문서가 몇개 있네요

2023-10-17 03:01 UTC, cocoyoon commented on ko/build/application-development.ko.md
> +다음 단계로 넘어가기
헠 클날뻔 했네요

2023-10-23 01:31 UTC, sweatpotato13 commented on ko/tutorials/build-a-blockchain/build-local-blockchain.ko.md
> +## ## 다음 단계로 넘어가기
`## ## 다음 단계로 넘어가기` -> `## 다음 단계로 넘어가기`

다른데도 동일한 이슈가 있어서 여기만 코멘트 남깁니다.

2023-10-23 01:42 UTC, sweatpotato13 reviewed
👍

2023-10-23 01:46 UTC, merged