Hugo
InfraBlockchain/infrablockspace-docs pull request #24
Opened 2023-10-26 04:45 UTC by energyGiver

# Overview
- system token
- system token weight 개요 및 계산 방법
- para fee rate 

# ToDo
- Tutorials: how to pay transcation fee (작성 중)
- Asset Link
- XCM configuration 수정사항

2023-10-26 05:07 UTC, sweatpotato13 requested changes
🐧

2023-10-26 05:07 UTC, sweatpotato13 commented on ko/infrablockchain/tutorials/create_token.png
root에 `media` 폴더가 있습니다. 이미지 파일은 그쪽에 넣어주세요

`media/images/docs/tutorials`

2023-10-30 04:59 UTC, sweatpotato13 commented on ko/infrablockchain/tutorials/how-to-pay-transaction-fee.md
> +media/images/docs/infrablockspace
붙여넣기가 이상한데 된 것 같아요

2023-10-30 05:00 UTC, sweatpotato13 commented on ko/infrablockchain/tutorials/how-to-pay-transaction-fee.md
> +media/images/docs/infrablockspace
Line 37

2023-10-30 05:07 UTC, cocoyoon commented on ko/infrablockchain/tutorials/how-to-pay-transaction-fee.md
> +## 1. 파라체인에 토큰 생성 및 발행하기
개인적으로는 번호 없는게 좋은거 같습니다.

2023-10-30 05:08 UTC, cocoyoon commented on ko/infrablockchain/tutorials/how-to-pay-transaction-fee.md
> +register_system_token을 거버넌스 올리기 위해 preimage에 먼저 등록을 해야합니다.
`bullet` 으로 처리하는게 좋아보입니다

2023-10-30 05:09 UTC, cocoyoon commented on ko/infrablockchain/tutorials/how-to-pay-transaction-fee.md
> +안건이 정상적으로 통과됐고, 파라체인에서도 sufficient = true로 바뀐 것을 확인할 수 있습니다.
문서에는 " `sufficient` 가 `true` " 라는 워딩으로 대체하는게 좋아보입니다.

2023-10-30 05:10 UTC, cocoyoon commented on ko/infrablockchain/tutorials/how-to-pay-transaction-fee.md
> +## 5. (선택) 다른 parachain에서 랩드 시스템 토큰 가스비로 사용하기
"등록된 시스템 토큰 사용하기" 는 어때요?

2023-10-30 05:13 UTC, sweatpotato13 commented on ko/infrablockchain/tutorials/how-to-pay-transaction-fee.md
> +## 5. (선택) 다른 parachain에서 랩드 시스템 토큰 가스비로 사용하기
`랩드` 라는 워딩이 한글로 써놓으면 어색하긴 하네요

2023-10-30 05:31 UTC, energyGiver commented on ko/infrablockchain/tutorials/how-to-pay-transaction-fee.md
> +## 1. 파라체인에 토큰 생성 및 발행하기
번호 없이 프리뷰 봤는데 단계 구분이 덜 되는 것 같아서 일단 놔뒀습니다!

2023-10-30 05:32 UTC, energyGiver commented on ko/infrablockchain/tutorials/how-to-pay-transaction-fee.md
> +register_system_token을 거버넌스 올리기 위해 preimage에 먼저 등록을 해야합니다.
1. 로 했을 때 프리뷰에서 구분이 잘 안 가서 h3(###)으로 바꿨습니다

2023-10-30 06:08 UTC, sweatpotato13 approved these changes
👍

2023-10-30 07:39 UTC, cocoyoon approved these changes

2023-10-30 07:46 UTC, merged