udpate docs
InfraBlockchain/infrablockspace-docs pull request #34
Opened 2023-11-13 23:04 UTC by bob202211

- checking semantic
- change english word to korea word

2023-11-14 01:33 UTC, cocoyoon requested changes
인프라 블록스페이스, 인프라 블록체인 용어들은 고유명사 형태로 적어주세요.

- 인프라 블록스페이스(InfraBlockspace) w/ Bold and Incline
- 인프라 블록체인(InfraBlockchain) w/ Bold and Incline

2023-11-14 01:47 UTC, bob202211 commented
수정했습니다~

> 인프라 블록스페이스, 인프라 블록체인 용어들은 고유명사 형태로 적어주세요.
> 
> * 인프라 블록스페이스(InfraBlockspace) w/ Bold and Incline
> * 인프라 블록체인(InfraBlockchain) w/ Bold and Incline

2023-11-14 01:50 UTC, cocoyoon commented on ko/infrablockchain/devops/build.md
> +컨테이너화는 애플리케이션의 코드를 모든 인프라에서 실행하는 데 필요한 모든 파일 및 라이브러리와 함께 번들로 제공하는 소프트웨어 배포 프로세스입니다. **_인프라 블록체인(InfraBlockchain)_**도 컨테이너화가 가능하며 관련 방법은 아래에 나와있습니다.
인프라 블록체인은 기술을 통칭하는거라 인프라 블록스페이스가 맞을거 같은데, 어떻게 생각하세요?

2023-11-14 01:50 UTC, cocoyoon commented on ko/infrablockchain/devops/build.md
> +https://github.com/InfraBlockchain
infrablockspace-sdk 링크로 보내야 하지 않아요?

2023-11-14 01:51 UTC, cocoyoon commented on ko/infrablockchain/devops/build.md
> +RUN rustup default nightly-2023-02-20
요것도 나중에는 저희 릴리즈 버전에서 사용한 nigthly 를 명시해주는게 좋겠죠?

2023-11-14 01:53 UTC, cocoyoon commented on ko/infrablockchain/devops/deploy.md
> +설명에 앞서, 이 문서에서는 네트워크를 통해 체인 스펙 파일을 다운로드받아 사용하는 방법만을 설명합니다. 만약 이렇게 진행을 원치않을 경우, 사용자께서 원하는 방법을 사용하셔서 chain spec 파일을 등록하시기를 바랍니다.
원하는 방법이 아래 나오는 방법들이죠?

2023-11-14 01:54 UTC, cocoyoon commented on ko/infrablockchain/devops/deploy.md
> +`<binary file>`은 릴레이 체인일때 infrablockspace를 입력해주면 되며, 파라체인은 infrablockspace-parachain을 입력해줍니다.
infra* "``" 요걸로 감싸주세요

2023-11-14 01:54 UTC, bob202211 commented on ko/infrablockchain/devops/build.md
> +컨테이너화는 애플리케이션의 코드를 모든 인프라에서 실행하는 데 필요한 모든 파일 및 라이브러리와 함께 번들로 제공하는 소프트웨어 배포 프로세스입니다. **_인프라 블록체인(InfraBlockchain)_**도 컨테이너화가 가능하며 관련 방법은 아래에 나와있습니다.
인프라 블록스페이스로 변경하는게 맞겠네여.

문구는 "인프라 블록스페이스에 속해있는 모든 체인들 또한, 컨테이너화가 가능하면~~~"
이런식으로 가면 괜찮을거 같은데 어떠신가요?

2023-11-14 01:55 UTC, bob202211 commented on ko/infrablockchain/devops/build.md
> +https://github.com/InfraBlockchain
저희 sdk 레포가 있었죠. 까먹고 있었네여 링크 수정해둘께여

2023-11-14 01:55 UTC, cocoyoon requested changes
해당 페이지에 _체인 스펙, 인프라 블록스페이스, 패러체인_ 같은 내용들이 나오니 
다른 페이지 참고하셔서 처음에 "시작하기전에: " 같은 섹션이나 맨 마지막에 "더 알아보기, 다음 단계로 넘어가기" 같은 섹션 추가해서 링크도 추가해주세요~

2023-11-14 01:56 UTC, cocoyoon commented on ko/infrablockchain/devops/build.md
> +컨테이너화는 애플리케이션의 코드를 모든 인프라에서 실행하는 데 필요한 모든 파일 및 라이브러리와 함께 번들로 제공하는 소프트웨어 배포 프로세스입니다. **_인프라 블록체인(InfraBlockchain)_**도 컨테이너화가 가능하며 관련 방법은 아래에 나와있습니다.
좋습니다 :)

2023-11-14 01:57 UTC, bob202211 commented on ko/infrablockchain/devops/build.md
> +RUN rustup default nightly-2023-02-20
네네 릴리즈 버전 나오면 그걸로 변경해둘께여
근데 지금 저 버전 안쓰고 계신가요? relay-chain 레포에 있는거 복사해온건데

2023-11-14 01:59 UTC, cocoyoon commented on ko/infrablockchain/devops/build.md
> +RUN rustup default nightly-2023-02-20
네 현재 마이그레이션 버전에서는 `nightly-2023-05-21` 사용하고 있어서 해당 버전으로 변경해서 작성해주는게 좋을거 같아요

2023-11-14 02:50 UTC, bob202211 commented
> 해당 페이지에 _체인 스펙, 인프라 블록스페이스, 패러체인_ 같은 내용들이 나오니 다른 페이지 참고하셔서 처음에 "시작하기전에: " 같은 섹션이나 맨 마지막에 "더 알아보기, 다음 단계로 넘어가기" 같은 섹션 추가해서 링크도 추가해주세요~

네네 추가해두겠습니다~

2023-11-14 02:50 UTC, bob202211 commented on ko/infrablockchain/devops/deploy.md
> +설명에 앞서, 이 문서에서는 네트워크를 통해 체인 스펙 파일을 다운로드받아 사용하는 방법만을 설명합니다. 만약 이렇게 진행을 원치않을 경우, 사용자께서 원하는 방법을 사용하셔서 chain spec 파일을 등록하시기를 바랍니다.
원하는 방법에 대해서는 작성을 안했는데 이 부분은 수정할께여

2023-11-15 04:44 UTC, cocoyoon commented on ko/infrablockchain/devops/deploy.md
> +-
Path 를 가능하면 `parity` 쪽 말고 내부 문서에서 끌어오는 방향으로 해주시면 좋을거같아요

2023-11-15 04:46 UTC, cocoyoon commented on ko/infrablockchain/devops/deploy.md
> +설명에 앞서, 이 문서에서는 네트워크를 통해 체인 스펙 파일을 다운로드받아 사용하는 방법만을 설명합니다. 만약 이렇게 진행을 원치않을 경우, 사용자께서 파일을 업로드하시거나 서버에서 직접 체인 스펙 파일을 만드시는 등 다양한 방법을 사용하셔서 체인 스펙 파일을 등록하시기를 바랍니다.
"사용자께서" 는 없어도 될거같아요

2023-11-15 04:46 UTC, bob202211 commented on ko/infrablockchain/devops/deploy.md
> +설명에 앞서, 이 문서에서는 네트워크를 통해 체인 스펙 파일을 다운로드받아 사용하는 방법만을 설명합니다. 만약 이렇게 진행을 원치않을 경우, 사용자께서 파일을 업로드하시거나 서버에서 직접 체인 스펙 파일을 만드시는 등 다양한 방법을 사용하셔서 체인 스펙 파일을 등록하시기를 바랍니다.
네넵

2023-11-15 04:49 UTC, merged